import { cookies } from "next/headers";
import { getPostgresDb } from "../db/postgres";
const COOKIE = "fala_session"; const encoder = new TextEncoder();
function hex(bytes: ArrayBuffer) { return [...new Uint8Array(bytes)].map((b) => b.toString(16).padStart(2, "0")).join(""); }
export async function hashPassword(password: string, salt = crypto.randomUUID()) { const key = await crypto.subtle.importKey("raw", encoder.encode(password), "PBKDF2", false, ["deriveBits"]); const bits = await crypto.subtle.deriveBits({ name: "PBKDF2", salt: encoder.encode(salt), iterations: 120000, hash: "SHA-256" }, key, 256); return `${salt}:${hex(bits)}`; }
export async function hashOpaqueToken(value: string) { return hex(await crypto.subtle.digest("SHA-256", encoder.encode(value))); }
export async function verifyPassword(password: string, stored: string) {
  const [salt, expected] = stored.split(":");
  if (!salt || !expected) return false;
  const actual = (await hashPassword(password, salt)).split(":")[1];
  if (actual.length !== expected.length) return false;
  let difference = 0;
  for (let index = 0; index < actual.length; index += 1) difference |= actual.charCodeAt(index) ^ expected.charCodeAt(index);
  return difference === 0;
}
export async function createSession(email: string, metadata?: { userAgent?: string; ip?: string }) { const token = crypto.randomUUID() + crypto.randomUUID().replaceAll("-", ""); const now = new Date(); const expires = new Date(now.getTime() + 2592000000); const db = getPostgresDb(); try { await db.prepare("INSERT INTO auth_sessions (token,user_email,created_at,expires_at,last_seen_at,user_agent,ip_address) VALUES (?,?,?,?,?,?,?)").bind(token, email, now.toISOString(), expires.toISOString(), now.toISOString(), metadata?.userAgent ?? null, metadata?.ip ?? null).run(); } catch (error) { if (/no such table|does not exist|column .* does not exist/i.test(String(error))) { try { await db.prepare("CREATE TABLE IF NOT EXISTS auth_sessions (token TEXT PRIMARY KEY NOT NULL,user_email TEXT NOT NULL,created_at TEXT NOT NULL,expires_at TEXT NOT NULL)").run(); } catch { /* migration is responsible for the durable schema */ } await db.prepare("INSERT INTO auth_sessions (token,user_email,created_at,expires_at) VALUES (?,?,?,?)").bind(token, email, now.toISOString(), expires.toISOString()).run(); } else throw error; } return { token, expires }; }
export async function invalidateSessions(email: string) { await getPostgresDb().prepare("DELETE FROM auth_sessions WHERE lower(user_email)=lower(?)").bind(email).run(); }
export async function getEmailSession() { const value = (await cookies()).get(COOKIE)?.value; if (!value) return null; const db = getPostgresDb(); const now = new Date().toISOString(); const inactiveCutoff = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(); try { const s = await db.prepare("SELECT u.email,u.display_name FROM auth_sessions s JOIN users u ON lower(u.email)=lower(s.user_email) WHERE s.token=? AND s.expires_at>? AND s.last_seen_at>? AND u.suspended_at IS NULL").bind(value, now, inactiveCutoff).first<{email:string;display_name:string}>(); if (s) await db.prepare("UPDATE auth_sessions SET last_seen_at=? WHERE token=?").bind(now, value).run(); return s ? { email: s.email, displayName: s.display_name, fullName: s.display_name } : null; } catch (error) { if (!/no such column|does not exist/i.test(String(error))) throw error; const s = await db.prepare("SELECT u.email,u.display_name FROM auth_sessions s JOIN users u ON lower(u.email)=lower(s.user_email) WHERE s.token=? AND s.expires_at>? AND u.suspended_at IS NULL").bind(value, now).first<{email:string;display_name:string}>(); return s ? { email: s.email, displayName: s.display_name, fullName: s.display_name } : null; } }
export const SESSION_COOKIE = COOKIE;
