const APP_URL = String(process.env.APP_URL || "https://fala-ai-three.vercel.app").replace(/\/$/, "");
const LOGO_URL = `${APP_URL}/favicon.svg`;

export function escapeHtml(value: unknown) {
  return String(value ?? "").replace(/[&<>\"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" })[character] ?? character);
}

function shell(title: string, preheader: string, content: string) {
  return `<!doctype html><html lang="fr"><head><meta name="color-scheme" content="light"><meta name="supported-color-schemes" content="light"></head><body style="margin:0;background:#f5f6f8;color:#171821;font-family:Arial,Helvetica,sans-serif"><div style="display:none;max-height:0;overflow:hidden;opacity:0">${escapeHtml(preheader)}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f5f6f8;padding:32px 12px"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;background:#fff;border:1px solid #e5e7eb;border-radius:16px;overflow:hidden"><tr><td style="padding:24px 28px;border-bottom:1px solid #eef0f3"><a href="${APP_URL}" style="text-decoration:none;color:#171821"><img src="${LOGO_URL}" width="36" height="36" alt="Fala AI" style="vertical-align:middle;border-radius:10px;margin-right:10px"><strong style="font-size:20px;vertical-align:middle">Fala AI</strong></a></td></tr><tr><td style="padding:32px 28px"><h1 style="font-size:24px;line-height:1.25;margin:0 0 18px;color:#171821">${escapeHtml(title)}</h1>${content}</td></tr><tr><td style="padding:20px 28px;background:#fafafa;border-top:1px solid #eef0f3;color:#6b7280;font-size:12px;line-height:1.6">Vous recevez ce message dans le cadre de votre compte Fala AI.<br><a href="${APP_URL}" style="color:#5131ea;text-decoration:none">Accéder à Fala AI</a> · Si vous n’êtes pas à l’origine de cette demande, aucune action n’est nécessaire.</td></tr></table></td></tr></table></body></html>`;
}

export function verificationEmail(code: string) {
  const safeCode = escapeHtml(code);
  return { subject: "Votre code d’accès Fala AI", text: `Bonjour,\n\nVoici votre code d’accès Fala AI : ${code}\n\nIl est valable 10 minutes. Si vous n’avez pas demandé ce code, vous pouvez ignorer ce message.\n\nL’équipe Fala AI`, html: shell("Confirmez votre adresse e-mail", "Votre code d’accès Fala AI est prêt.", `<p style="font-size:16px;line-height:1.6;margin:0 0 18px">Bonjour,</p><p style="font-size:16px;line-height:1.6;margin:0 0 22px">Saisissez le code ci-dessous dans Fala AI pour confirmer votre adresse et poursuivre votre inscription.</p><p style="margin:0 0 22px;text-align:center"><span style="display:inline-block;padding:16px 24px;border:1px solid #ddd6fe;border-radius:12px;background:#f5f3ff;color:#3f2b9e;font-size:32px;letter-spacing:8px;font-weight:700">${safeCode}</span></p><p style="font-size:13px;line-height:1.6;color:#6b7280;margin:0">Ce code expire dans 10 minutes. Pour votre sécurité, ne le partagez avec personne.</p>`) };
}

export function resetEmail(resetUrl: string) {
  const safeUrl = escapeHtml(resetUrl);
  return { subject: "Modifier votre mot de passe Fala AI", text: `Bonjour,\n\nUne demande de modification du mot de passe de votre compte Fala AI a été reçue.\n\nOuvrez ce lien pour choisir un nouveau mot de passe : ${resetUrl}\n\nCe lien est valable 1 heure et ne peut être utilisé qu’une seule fois.\n\nL’équipe Fala AI`, html: shell("Modifiez votre mot de passe", "Un lien sécurisé pour modifier votre mot de passe Fala AI.", `<p style="font-size:16px;line-height:1.6;margin:0 0 18px">Bonjour,</p><p style="font-size:16px;line-height:1.6;margin:0 0 24px">Une demande de modification du mot de passe de votre compte Fala AI a été reçue.</p><p style="margin:0 0 24px"><a href="${safeUrl}" style="display:inline-block;padding:13px 20px;border-radius:10px;background:#5131ea;color:#fff;text-decoration:none;font-weight:700">Choisir un nouveau mot de passe</a></p><p style="font-size:13px;line-height:1.6;color:#6b7280;margin:0">Ce lien est valable 1 heure et ne peut être utilisé qu’une seule fois. Si vous n’êtes pas à l’origine de cette demande, vous pouvez ignorer ce message.</p>`) };
}

export function interviewEmail(name: string, role: string, company: string, date: string) {
  const safeName = escapeHtml(name || ""); const safeRole = escapeHtml(role); const safeCompany = escapeHtml(company); const safeDate = escapeHtml(date);
  return { subject: `Fala AI — Rappel d’entretien : ${role}`, text: `Bonjour ${name || ""},\n\nUn entretien est prévu pour le poste « ${role} » chez ${company}.\n\nDate : ${date}\n\nConnectez-vous à votre espace Fala AI pour consulter les détails de la candidature et préparer votre échange.\n\nL’équipe Fala AI`, html: shell("Votre entretien approche", "Un rappel Fala AI concernant un entretien est disponible.", `<p style="font-size:16px;line-height:1.6;margin:0 0 18px">Bonjour ${safeName},</p><p style="font-size:16px;line-height:1.6;margin:0 0 22px">Un entretien est prévu dans votre espace Fala AI pour la candidature suivante :</p><table role="presentation" cellspacing="0" cellpadding="0" width="100%" style="background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;margin:0 0 24px"><tr><td style="padding:16px"><strong style="display:block;font-size:17px;margin-bottom:6px">${safeRole}</strong><span style="display:block;color:#4b5563;margin-bottom:5px">${safeCompany}</span><span style="display:block;color:#4b5563">${safeDate}</span></td></tr></table><p style="margin:0 0 24px"><a href="${APP_URL}" style="display:inline-block;padding:13px 20px;border-radius:10px;background:#5131ea;color:#fff;text-decoration:none;font-weight:700">Ouvrir ma candidature</a></p><p style="font-size:13px;line-height:1.6;color:#6b7280;margin:0">Vous pourrez consulter les informations disponibles et préparer votre échange depuis votre espace personnel.</p>`) };
}
