import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const profiles = sqliteTable("profiles", {
  userEmail: text("user_email").primaryKey(),
  targetTitle: text("target_title").notNull().default(""),
  location: text("location").notNull().default(""),
  contractType: text("contract_type").notNull().default(""),
  skills: text("skills").notNull().default(""),
  experienceLevel: text("experience_level").notNull().default(""),
  educationLevel: text("education_level").notNull().default(""),
  languages: text("languages").notNull().default(""),
  sectors: text("sectors").notNull().default(""),
  salaryMin: integer("salary_min").notNull().default(0),
  updatedAt: text("updated_at").notNull(),
});

export const applications = sqliteTable("applications", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userEmail: text("user_email").notNull(),
  company: text("company").notNull(),
  role: text("role").notNull(),
  location: text("location").notNull().default(""),
  contractType: text("contract_type").notNull().default(""),
  source: text("source").notNull().default("Ajout manuel"),
  requiredSkills: text("required_skills").notNull().default(""),
  experienceRequired: text("experience_required").notNull().default(""),
  educationRequired: text("education_required").notNull().default(""),
  languages: text("languages").notNull().default(""),
  sector: text("sector").notNull().default(""),
  salaryMin: integer("salary_min").notNull().default(0),
  status: text("status").notNull().default("À préparer"),
  appliedAt: text("applied_at"),
  nextActionAt: text("next_action_at"),
  interviewAt: text("interview_at"),
  score: integer("score"),
  scoreBreakdown: text("score_breakdown"),
  notes: text("notes").notNull().default(""),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});
