-- Runtime schema used by the Vercel application. Execute migrations in
-- filename order in Supabase SQL Editor (or through the Supabase CLI).
-- Every statement is idempotent so a partially initialized project can be
-- repaired without dropping user data.

create table if not exists public.users (
  email text primary key,
  display_name text not null,
  created_at timestamptz not null,
  last_seen_at timestamptz not null,
  consent_version text,
  consented_at timestamptz,
  suspended_at timestamptz,
  suspension_reason text,
  password_hash text,
  email_verified_at timestamptz,
  verification_token text,
  reset_token text,
  reset_token_expires_at timestamptz
);

create table if not exists public.auth_sessions (
  token text primary key,
  user_email text not null references public.users(email) on delete cascade,
  created_at timestamptz not null,
  expires_at timestamptz not null
);

create table if not exists public.rate_limits (
  key text primary key,
  window_start timestamptz not null,
  count integer not null default 0
);

create table if not exists public.activity_events (
  id bigint generated by default as identity primary key,
  user_email text not null references public.users(email) on delete cascade,
  event_type text not null,
  description text not null,
  created_at timestamptz not null
);

create table if not exists public.profiles (
  user_email text primary key references public.users(email) on delete cascade,
  target_title text not null default '',
  location text not null default '',
  contract_type text not null default '',
  skills text not null default '',
  experience_level text not null default '',
  education_level text not null default '',
  languages text not null default '',
  sectors text not null default '',
  salary_min integer not null default 0,
  updated_at timestamptz not null
);

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  user_email text not null references public.users(email) on delete cascade,
  company text not null,
  role text not null,
  location text not null default '',
  contract_type text not null default '',
  source text not null default 'Ajout manuel',
  required_skills text not null default '',
  experience_required text not null default '',
  education_required text not null default '',
  languages text not null default '',
  sector text not null default '',
  salary_min integer not null default 0,
  status text not null default 'À préparer',
  applied_at timestamptz,
  next_action_at timestamptz,
  interview_at timestamptz,
  score integer,
  score_breakdown text,
  notes text not null default '',
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists public.user_roles (
  user_email text not null references public.users(email) on delete cascade,
  role text not null,
  granted_by text not null,
  created_at timestamptz not null
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  user_email text not null references public.users(email) on delete cascade,
  category text not null,
  message text not null,
  status text not null default 'open',
  admin_note text not null default '',
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists public.system_errors (
  id bigint generated by default as identity primary key,
  user_email text references public.users(email) on delete set null,
  route text not null,
  message text not null,
  created_at timestamptz not null
);

create table if not exists public.notification_preferences (
  user_email text primary key references public.users(email) on delete cascade,
  enabled boolean not null default false,
  updated_at timestamptz not null,
  last_notified_at timestamptz
);

create table if not exists public.auth_login_failures (
  identity text primary key not null,
  failed_count integer not null default 0,
  first_failed_at timestamptz not null,
  locked_until timestamptz,
  updated_at timestamptz not null
);

create index if not exists applications_user_email_idx on public.applications(user_email);
create index if not exists activity_events_user_email_idx on public.activity_events(user_email, id desc);
create index if not exists auth_sessions_user_email_idx on public.auth_sessions(user_email);
create index if not exists reports_user_email_idx on public.reports(user_email);

revoke all on all tables in schema public from anon, authenticated;
